data_path = "/home/aa043/sea/data/td/ours/v2/classify/"

# Use the files generated by JavaParser to extract plain code segments
with open(data_path+"neg_code/Codes.java", 'r', encoding='utf-8') as f:
    neg_code_lines = f.read().split("\n")
with open(data_path+"pos_code/Codes.java", 'r', encoding='utf-8') as f:
    pos_code_lines = f.read().split("\n")

# Retrieve only the if-statements
neg_codes = []
for line in neg_code_lines:
    if line.startswith("\tif"):
        neg_codes.append(line[1:])
pos_codes = []
for line in pos_code_lines:
    if line.startswith("\tif"):
        pos_codes.append(line[1:])

# Save code segments to disk
with open(data_path+"plain_code/neg_codes.txt", "w", encoding='utf-8') as f:
    for line in neg_codes:
        f.write(line+"\n")
with open(data_path+"plain_code/pos_codes.txt", "w", encoding='utf-8') as f:
    for line in pos_codes:
        f.write(line+"\n")
